[general]
import = [
"~/.config/alacritty/gruvbox.toml",
]

[window]
opacity = 0.7
padding = {x = 5, y = 5}
blur = true
title = "term"

[font]
normal = {family = "IosevkaNerdFont", style = "Bold"}
size = 13

[selection]
save_to_clipboard = true

[cursor]
style = {shape = "Beam", blinking = "Off"}

[mouse]
hide_when_typing = true
