[mgr]
ratio = [1, 2, 3]
sort_by = "natural"
sort_sensitive = true
sort_reverse = false
sort_dir_first = true
sort_translit = true
linemode = "size"
show_hidden = true
show_symlink = true
scrolloff = 8
title_format = "yazi {cwd}"
  keymap = [
    { on = "u", run = "plugin restore", desc = "Restore last deleted files/folders" },
    # or use "d + u" like me
    { on = ["d", "u"], run = "plugin restore", desc = "Restore last deleted files/folders" },

    # Select files/folders to restore. Input item index or range separated by comma:
    # - Restore a trashed file:
    #      What file to restore [0..4]: 4
    # - Restore multiple trashed files separated by comma, also support range:
    #      What file to restore [0..3]: 0-2, 3

    # Remove --overwrite if you don't want to overwrite existed files and this will abort restoring when there is existed file.
    { on = [ "d", "U" ], run = "shell --block -- clear && trash-restore --overwrite", desc = "Restore deleted file (Interactive)" },
    # ... Other keymaps
  ]

[preview]
wrap = "yes"
tab_size = 2
max_width = 640
max_height = 480
cache_dir = "$HOME/.config/yazi/.cache/"
image_filter = "triangle"
image_quality = 65

[opener]
play = [{run = 'mpv "$@"', orphan = true, for = "unix"}]
edit = [{run = 'nvim "$@"', block = true, for = "unix"}]
open = [{run = 'xdg-open "$@"', desc = "Open"}]

[tasks]
micro_workers = 5
macro_workers = 10
suppress_preload = true
image_alloc = 20971520
image_bound = [2048, 2048]

[plugin]
prepend_previewers = [
	# Archive previewer
	{ mime = "application/*zip",            run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
	{ mime = "application/x-xz",            run = "ouch" },
	{ mime = "application/xz",              run = "ouch" },
]
